import pytest
from unittest.mock import patch
from ai_text_verifier import verify_text

def test_verify_text_human():
    text = "This is a human-written sentence."
    with patch("ai_text_verifier.pipeline") as mock_pipeline:
        mock_pipeline.return_value = lambda x: [[[0.1, 0.2, 0.3]]]
        with patch("ai_text_verifier.TfidfVectorizer") as mock_vectorizer:
            mock_vectorizer.return_value.fit_transform.return_value = [[0.1, 0.2, 0.3]]
            mock_vectorizer.return_value.transform.return_value = [[0.1, 0.2, 0.3]]
            with patch("ai_text_verifier.LogisticRegression") as mock_classifier:
                mock_classifier.return_value.predict_proba.return_value = [[0.9, 0.1]]
                result = verify_text(text)
                assert result == pytest.approx(0.1)

def test_verify_text_ai():
    text = "Generated by AI."
    with patch("ai_text_verifier.pipeline") as mock_pipeline:
        mock_pipeline.return_value = lambda x: [[[0.4, 0.5, 0.6]]]
        with patch("ai_text_verifier.TfidfVectorizer") as mock_vectorizer:
            mock_vectorizer.return_value.fit_transform.return_value = [[0.4, 0.5, 0.6]]
            mock_vectorizer.return_value.transform.return_value = [[0.4, 0.5, 0.6]]
            with patch("ai_text_verifier.LogisticRegression") as mock_classifier:
                mock_classifier.return_value.predict_proba.return_value = [[0.2, 0.8]]
                result = verify_text(text)
                assert result == pytest.approx(0.8)

def test_verify_text_empty_input():
    text = ""
    with pytest.raises(ValueError):
        verify_text(text)
