import argparse
import os
import xml.etree.ElementTree as ET
from rich.console import Console
from rich.table import Table
import openai

def analyze_coverage(report_path):
    """
    Analyze the coverage report and return uncovered files and lines.

    Args:
        report_path (str): Path to the coverage XML report.

    Returns:
        dict: A dictionary with file paths as keys and uncovered lines as values.
    """
    if not os.path.exists(report_path):
        raise FileNotFoundError(f"Coverage report file not found: {report_path}")

    uncovered = {}
    with open(report_path, "r") as file:
        tree = ET.parse(file)
        root = tree.getroot()

        for file_elem in root.findall(".//class"):
            filename = file_elem.get("filename")
            lines_elem = file_elem.find("lines")
            if lines_elem is not None:
                uncovered_lines = []
                for line in lines_elem.findall("line"):
                    if line.get("hits") == "0":
                        uncovered_lines.append(int(line.get("number")))
                if uncovered_lines:
                    uncovered[filename] = uncovered_lines

    return uncovered

def generate_ai_suggestions(uncovered):
    """
    Use OpenAI API to generate suggestions for improving test coverage.

    Args:
        uncovered (dict): Dictionary of uncovered files and lines.

    Returns:
        dict: AI-generated suggestions for each file.
    """
    suggestions = {}
    openai.api_key = os.getenv("OPENAI_API_KEY")

    for filename, lines in uncovered.items():
        prompt = (
            f"The following lines in the file '{filename}' are not covered by tests: {lines}. "
            "Please provide suggestions for test cases to improve coverage in these areas."
        )
        try:
            response = openai.Completion.create(
                engine="text-davinci-003",
                prompt=prompt,
                max_tokens=150
            )
            suggestions[filename] = response["choices"][0]["text"].strip()
        except Exception as e:
            suggestions[filename] = f"Error generating suggestion: {e}"

    return suggestions

def display_results(uncovered, suggestions):
    """
    Display uncovered lines and AI suggestions in a table format.

    Args:
        uncovered (dict): Dictionary of uncovered files and lines.
        suggestions (dict): AI-generated suggestions for each file.
    """
    console = Console()
    table = Table(title="Test Coverage Analysis and Suggestions")

    table.add_column("File", style="cyan", no_wrap=True)
    table.add_column("Uncovered Lines", style="magenta")
    table.add_column("AI Suggestions", style="green")

    for filename, lines in uncovered.items():
        suggestion = suggestions.get(filename, "No suggestion available")
        table.add_row(filename, ", ".join(map(str, lines)), suggestion)

    console.print(table)

def main():
    parser = argparse.ArgumentParser(
        description="Analyze test coverage reports and get AI-driven suggestions for improving test cases."
    )
    parser.add_argument(
        "--report",
        required=True,
        help="Path to the coverage XML report generated by coverage.py",
    )

    args = parser.parse_args()

    try:
        uncovered = analyze_coverage(args.report)
        if not uncovered:
            print("Great job! All lines are covered by tests.")
            return

        suggestions = generate_ai_suggestions(uncovered)
        display_results(uncovered, suggestions)
    except FileNotFoundError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()
